export default {
    projects: [
        {
            id: 1,
            image: 'img/GrowingUp.png',
            image_alt: 'Growing Up Screenshot',
            name: 'Growing Up',
            description: `Growing up is the app that grows with your family. It allows parents to easily track and monitor their child's eating and sleeping habits. Parents can start new feeding and sleeping sessions, add details about how well they slept or what they at, and see a list of last sessions and their details.`,
            tech: 'HTML, CSS, JavaScript, React, Node.js, SQL, PostgreSQL',
            live_app: 'https://growing-up.vercel.app/',
            client: 'https://github.com/makowilliams/growing-up',
            server: 'https://github.com/halemd30/growing-up-server',
            repo: '',
        },
        {
            id: 2,
            image: 'img/Traveler_LandingPage.png',
            image_alt: 'Travler Screenshot',
            name: 'Traveler',
            description: 'Traveler allows users to create and browse reviews of things to do on a trip. They can then take those ideas and create, edit, and save a trip itinerary.',
            tech: 'HTML, CSS, JavaScript, React, Node.js, SQL, PostgreSQL',
            live_app: 'https://traveler.now.sh/',
            client: 'https://github.com/holly257/traveler',
            server: 'https://github.com/holly257/traveler-api',
            repo: '',
        },
        {
            id: 3,
            image: 'img/Noteful.png',
            image_alt: 'Noteful Screenshot',
            name: 'Noteful',
            description: 'Full stack app that enables users to create their own notes, store them in folders, and update them as needed. It incorporates React Router, PostgreSQL database and uses context to keep user data up to date in each route.',
            tech: 'HTML, CSS, JavaScript, React, Node.js, SQL, PostgreSQL',
            live_app: 'https://noteful-client-psi-three.now.sh/',
            client: '',
            server: '',
            repo: 'https://github.com/holly257/noteful',
        },
        {
            id: 4,
            image: 'img/ScreenShot1.png',
            image_alt: 'Munch Map Screenshot',
            name: 'Munch Map',
            description: 'Munch Map takes a users input and returns options for resturants in the designated location.',
            tech: 'HTML, CSS, JavaScript, REST API, jQuery',
            live_app: 'https://holly257.github.io/APIhack-restaurantMap/',
            client: '',
            server: '',
            repo: 'https://github.com/holly257/APIhack-restaurantMap',
        },
        {
            id: 5,
            image: 'img/GoogleBookSearch-Dog.png',
            image_alt: 'Google Book Search Dog',
            name: 'Book Search',
            description: 'Allows users to find information on books by using the Google Books API and returning data. Users can refine their search requests by both print type and book type.',
            tech: 'HTML, CSS, JavaScript, REST API, React',
            live_app: 'https://noteful-client-psi-three.now.sh/',
            client: '',
            server: '',
            repo: 'https://github.com/holly257/book-search',
        },
    ]
}